#MAPPING
OUTDIR : /home2/adefalco/LiquidBiopsy_Data/cfMedip/07_2025_genomix/output_folder #Output folder
DATDIR : /home2/adefalco/LiquidBiopsy_Data/cfMedip/ #Fastq Data Folder (EX. DATADIT/EXP/SAMPTYPE -> HOME/DATI/GSE87096/CONTROL - HOME/DATI/GSE87096/CRC)
#INDEX : /storage/gluster/vol1/SHARED/NGSTOOLS/BCBIO/bcbio/genomes/Hsapiens/hg38/bowtie2 #Hg38 Reference Index
INDEX : /storage/qnap_vol1/SHARED/NGSTOOLS/BCBIO/bcbio/genomes/Hsapiens/hg38/bowtie2
SAMTOOLSPATH : /storage/qnap_vol1/SHARED/NGSTOOLS/BCBIO/bcbio/anaconda/bin/samtools #Samtools PATH
BOWTIE2PATH : /storage/qnap_vol1/SHARED/NGSTOOLS/BCBIO/bcbio/anaconda/bin/bowtie2 #Bowtie2 PATH
FASTQCPATH : export PATH="/home/adefalco/cfBreast/FastQC:$PATH"
CUTADAPTPATH: /storage/qnap_vol1/SHARED/NGSTOOLS/BCBIO2023/anaconda/envs/python2/bin/cutadapt
TRIMGALOREPATH: /storage/qnap_home/tufano/tools/TrimGalore-0.6.6/trim_galore

GENOME_index: "hg38"
PAIRED: True
PATH_FASTQ : "/home2/adefalco/LiquidBiopsy_Data/cfMedip/07_2025_genomix/RAW_DATA/"
FASTQ_SUFFIXES:
    1_SUFFIX : "R1_001.fastq.gz"
    2_SUFFIX : "R2_001.fastq.gz" 
NUM_THREADS : 40

#createMedipObj
WS : 300 #Window size
GENOME : "BSgenome.Hsapiens.UCSC.hg38" #Genome reference

#DMRclassification
METHOD : "glmnet" #or rf (random forest)
MODELSELECTION : "LeaveOneOut" #or ShuffleSplit
#IF MODEL is ShuffleSplit
#N_SPLITS : 10

#Datasets
EXP :
  - "07_2025_genomix"

#Sample types in each dataset
SAMPTYPE : 
  07_2025_genomix:
    - Melanoma
    - Breast

EXCLUDE_SAMPLES:
